# Generated by Django 5.2.17 on 2026-08-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performance",
            options={"ordering": ("-show_time",)},
        ),
    ]
